### PR TITLE
Thread annotations through all type models

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by blampe** [comment]
wut dis 4

**Comment by kriskowal** [comment]
@blampe To get this out of my working copy. Rui inquired about being able to introspect annotations on thrift models. Support for this is inconsistent.

**Comment by abhinav** [comment]
:+1:

**Comment by blampe** [comment]
Putting this on the back burner until we have a plan for cross-language feature parity.

**Comment by kriskowal** [comment]
@blampe I think we should reconsider this.

**Comment by abhinav** [comment]
FYI with thriftrw/thriftrw-go#243 and thriftrw/thriftrw-go#195, thriftrw-go now exposes all annotations in the compilation layer (but at runtime or in the generated code).

**Pull request merged**
